source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCActivityButton' do
  pod "MCActivityButton", :path => "../"
end

target 'Tests' do
  pod "MCActivityButton", :path => "../"
end
